In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 25 ms


In [11]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 807 ms


The NumPy ndarray: A Multidimensional Array Object

In [16]:
data = np.random.randn(2,3) # 2*3 的数据结构

In [17]:
data

array([[-1.5598683 , -1.99330188,  1.8455636 ],
       [-1.63588153, -0.37266901,  0.99696573]])

In [18]:
data * 10

array([[-15.59868302, -19.93301877,  18.45563596],
       [-16.35881529,  -3.72669007,   9.9696573 ]])

In [19]:
data + data

array([[-3.1197366 , -3.98660375,  3.69112719],
       [-3.27176306, -0.74533801,  1.99393146]])

In [20]:
data.shape

(2, 3)

In [21]:
data.dtype

dtype('float64')

In [22]:
data1 = [6, 7.5, 8, 0, 1]

In [23]:
arr1 = np.array(data1)

In [24]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [25]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [26]:
arr2 = np.array(data2)

In [27]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr1.ndim

1

In [32]:
arr2.ndim

2

In [34]:
arr1.shape

(5,)

In [35]:
arr2.shape

(2, 4)

In [36]:
arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int32')

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
np.empty((2,3,2)) #不建议用empty，可能会return奇奇怪怪的东西

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [42]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
arr1 = np.array([1, 2, 3], dtype=np.float32)

In [44]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [46]:
arr1.dtype

dtype('float32')

In [47]:
arr2.dtype

dtype('int32')

In [48]:
arr = np.array([1, 2, 3, 4, 5])

In [49]:
arr.dtype

dtype('int32')

In [50]:
float_arr = arr.astype(np.float64)

In [51]:
arr.dtype

dtype('int32')

In [52]:
float_arr.dtype

dtype('float64')

In [56]:
numeric_strings = np.array(['1.25', '-9.6', '0'], dtype=np.string_)

In [57]:
numeric_strings.astype(float)

array([ 1.25, -9.6 ,  0.  ])

In [61]:
int_array = np.arange(10)

In [62]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [63]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
empty_uint32 = np.empty(8, dtype='u4')

In [65]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [66]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])

In [67]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [69]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
arr2 = np.array([[0, 4, 1.], [7., 2., 12.]])

In [71]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [73]:
type(arr2>arr)

numpy.ndarray

In [74]:
arr = np.arange(10)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[5]

5

In [77]:
arr[5:8]

array([5, 6, 7])

In [78]:
arr[5:8]

array([5, 6, 7])

In [79]:
arr[5:8] = 12

In [80]:
arr[5:8]

array([12, 12, 12])

In [81]:
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [89]:
arr_slice = arr[5:8]

In [90]:
arr_slice

array([   12, 12345,    12])

In [91]:
arr_slice[1] = 12345

In [92]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [93]:
arr_slice[:] = 64

In [94]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [95]:
arr_slice_2 = arr_slice.copy()

In [96]:
arr_slice_2

array([64, 64, 64])

In [97]:
arr_slice_2[1] = 32

In [98]:
arr_slice_2

array([64, 32, 64])

In [99]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [100]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [101]:
arr2d[2]

array([7, 8, 9])

In [102]:
arr2d[2][2]

9

In [103]:
arr2d[2,2]

9

In [120]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [121]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [122]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
old_values = arr3d[0].copy()

In [124]:
arr3d[0] = 42

In [125]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [126]:
arr3d[0][1]

array([42, 42, 42])

In [127]:
arr3d[0] = old_values

In [128]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [129]:
arr3d[0][1]

array([4, 5, 6])

In [130]:
arr3d[0][1][1]

5

In [131]:
x = arr3d[1]

In [132]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [133]:
x[0]

array([7, 8, 9])

In [134]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [135]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [136]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [139]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [140]:
data = np.random.randn(7,4)

In [141]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [142]:
data

array([[-0.09549803,  0.12874571,  0.4127563 , -0.78273442],
       [-0.39881225, -0.86466323,  0.92124565,  0.65832166],
       [-1.20034056,  0.28620823, -0.9250486 , -1.20631907],
       [-1.11615993, -0.45170214,  1.15269476, -1.04718318],
       [-2.73795672, -1.15932845, -0.19861567, -0.61883218],
       [-0.19676212,  0.00573384, -0.98860413,  0.41418883],
       [ 2.69863505,  0.06578729, -0.20831436,  0.64028488]])

In [143]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [145]:
data[names=='Bob'] #The boolean array must be of the same length as the array axis it’s indexing.

array([[-0.09549803,  0.12874571,  0.4127563 , -0.78273442],
       [-1.11615993, -0.45170214,  1.15269476, -1.04718318]])

In [147]:
data[names=='Bob', 2:]

array([[ 0.4127563 , -0.78273442],
       [ 1.15269476, -1.04718318]])

In [149]:
data[names=='Bob', 3]

array([-0.78273442, -1.04718318])

In [153]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [154]:
data[~(names=='Bob')]

array([[-0.39881225, -0.86466323,  0.92124565,  0.65832166],
       [-1.20034056,  0.28620823, -0.9250486 , -1.20631907],
       [-2.73795672, -1.15932845, -0.19861567, -0.61883218],
       [-0.19676212,  0.00573384, -0.98860413,  0.41418883],
       [ 2.69863505,  0.06578729, -0.20831436,  0.64028488]])

In [155]:
cond = names =='Bob'

In [156]:
data[cond]

array([[-0.09549803,  0.12874571,  0.4127563 , -0.78273442],
       [-1.11615993, -0.45170214,  1.15269476, -1.04718318]])

In [157]:
data[~cond]

array([[-0.39881225, -0.86466323,  0.92124565,  0.65832166],
       [-1.20034056,  0.28620823, -0.9250486 , -1.20631907],
       [-2.73795672, -1.15932845, -0.19861567, -0.61883218],
       [-0.19676212,  0.00573384, -0.98860413,  0.41418883],
       [ 2.69863505,  0.06578729, -0.20831436,  0.64028488]])

In [159]:
data[data<0]=0

In [160]:
data

array([[0.        , 0.12874571, 0.4127563 , 0.        ],
       [0.        , 0.        , 0.92124565, 0.65832166],
       [0.        , 0.28620823, 0.        , 0.        ],
       [0.        , 0.        , 1.15269476, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.00573384, 0.        , 0.41418883],
       [2.69863505, 0.06578729, 0.        , 0.64028488]])

In [161]:
data[names!='Joe']=7

In [162]:
data

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 9.21245651e-01, 6.58321655e-01],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [0.00000000e+00, 5.73384163e-03, 0.00000000e+00, 4.14188826e-01],
       [2.69863505e+00, 6.57872905e-02, 0.00000000e+00, 6.40284878e-01]])

In [163]:
arr = np.empty((8, 4))

In [165]:
for i in range(8):
    arr[i] = i

In [166]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [168]:
arr[1]

array([1., 1., 1., 1.])

In [169]:
arr[[4, 3, 0, 6]] # 这些数字表示的是行

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [170]:
arr = np.arange(32).reshape((8, 4))

In [171]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [172]:
arr[[1, 5, 7, 2],[0, 3, 1, 2]] #分别是x,y坐标

array([ 4, 23, 29, 10])

In [175]:
arr[[1, 5, 7, 2]][:3, [0, 3, 1]] # 前面选择行, 后面选择列，并且可以选择列的顺序(位置为实际位置)

array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29]])

In [176]:
arr[[1, 5, 7, 2]][:3, [0, 2, 1]]

array([[ 4,  6,  5],
       [20, 22, 21],
       [28, 30, 29]])

In [177]:
arr = np.arange(15).reshape((3, 5))

In [178]:
arr.T # 取反，做矩阵运算经常用

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [179]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [180]:
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [181]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [182]:
arr = np.arange(16).reshape((2, 2, 4))

In [183]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [184]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [185]:
arr.transpose((2, 0, 1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [186]:
arr.swapaxes(0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [187]:
arr = np.random.randn(7)*5

In [188]:
remainder, whole_part = np.modf(arr)

In [189]:
remainder

array([ 0.66147809, -0.26582919, -0.81787772,  0.16040138,  0.27064666,
        0.74776237,  0.6364508 ])

In [190]:
whole_part

array([ 7., -5., -1.,  0.,  2.,  2.,  1.])

In [191]:
np.sqrt(arr, arr) # 后面一个代表in-place

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.76793751,        nan,        nan, 0.40050141, 1.5068665 ,
       1.65763759, 1.27923837])